title: 제이슨의 프로그래밍 다이어리(Zayson's Programming Diary)
description: Zayson's Blog Since 20.11.02
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jymaeng95/github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Joon Young Maeng (Zayson)
author-image:   zayson.jpg
author-job:     Web Backend Developer
author-email:   jymaeng95@gmail.com # Add your email for contant form.
author-instagram:  # Add your twitter account
about-author:   성장하기 위해 학습하는 웹 백엔드 개발자 지망생입니다. 
# Social settings
social-twitter:   
social-facebook:  profile.php?id=100004769082977
social-github:    jymaeng95
social-pinterest: 
social-instagram: __zayson
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
